steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/golden-rules-app:latest', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/golden-rules-app:latest']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'golden-rules-app'
      - '--image=gcr.io/$PROJECT_ID/golden-rules-app:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--set-env-vars=DATABASE_URL=file:./prisma/golden_rules.db,NODE_ENV=production'
      - '--set-volumes=name=db-volume,mount-path=/app/prisma,type=cloud-storage,bucket=goldenrulesnextjs-db'

images:
  - 'gcr.io/$PROJECT_ID/golden-rules-app:latest'
