apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/client-name: gcloud
    run.googleapis.com/client-version: 527.0.0
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/operation-id: e0f226a1-3bc8-4b8a-a9ab-15f19f7fd2a2
    run.googleapis.com/urls: '["https://golden-rules-app-733970662312.us-central1.run.app","https://golden-rules-app-yp3b4auata-uc.a.run.app"]'
    serving.knative.dev/creator: 733970662312-compute@developer.gserviceaccount.com
    serving.knative.dev/lastModifier: 733970662312-compute@developer.gserviceaccount.com
  creationTimestamp: '2025-06-22T21:50:59.326046Z'
  generation: 1
  labels:
    cloud.googleapis.com/location: us-central1
  name: golden-rules-app
  namespace: '733970662312'
  resourceVersion: AAY4MBhd7Dg
  selfLink: /apis/serving.knative.dev/v1/namespaces/733970662312/services/golden-rules-app
  uid: 674632a5-55e9-4b16-83ab-2ae6ef5d11ca
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '20'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 527.0.0
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: tmxgnmiabm
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: DATABASE_URL
          value: file:./golden_rules.db
        - name: NODE_ENV
          value: production
        image: us-central1-docker.pkg.dev/smart-inn-450817-m9/golden-rules-repo/golden-rules-app:latest
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: 733970662312-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
status:
  address:
    url: https://golden-rules-app-yp3b4auata-uc.a.run.app
  conditions:
  - lastTransitionTime: '2025-06-22T21:51:18.658104Z'
    status: 'True'
    type: Ready
  - lastTransitionTime: '2025-06-22T21:51:17.396674Z'
    status: 'True'
    type: ConfigurationsReady
  - lastTransitionTime: '2025-06-22T21:51:18.628597Z'
    status: 'True'
    type: RoutesReady
  latestCreatedRevisionName: golden-rules-app-00001-vmm
  latestReadyRevisionName: golden-rules-app-00001-vmm
  observedGeneration: 1
  traffic:
  - latestRevision: true
    percent: 100
    revisionName: golden-rules-app-00001-vmm
  url: https://golden-rules-app-yp3b4auata-uc.a.run.app
